services:
  db:
    image: pgvector/pgvector:pg16
    container_name: db
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare
    volumes:
      - /mnt/postgres:/var/lib/postgresql/data 
      - ./db-init:/docker-entrypoint-initdb.d 
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      retries: 5
  app:
    build: .
    ports:
      - "3000:3000"
    env_file: .env.prod
    environment:
      TRANSFORMERS_CACHE: ${TRANSFORMERS_CACHE}
      USE_ONNXRUNTIME_NODE: "0"
    volumes:
      - huggingface:${TRANSFORMERS_CACHE}
    depends_on:
      db:
        condition: service_healthy
      # rabbitmq:  # using CloudAMQP instead
      #   condition: service_started
    restart: unless-stopped

  # rabbitmq:  # using CloudAMQP instead
  #   image: rabbitmq:management-alpine
  #   ports:
  #     - "5672:5672"
  #     - "15672:15672"
  #   env_file: .env.prod
  #   volumes:
  #     - rabbitmq_data:/var/lib/rabbitmq/data

volumes:
  huggingface:
  # rabbitmq_data:  # using CloudAMQP instead
