services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: healthcare
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d
    ports: ["5432:5432"]

  app:
    build: .
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
        - action: rebuild
          path: package.json
    ports:       
      - "3000:3000"
    env_file: .env
    environment:
      POSTGRES_URI: postgres://postgres:postgres@db:5432/healthcare
      TRANSFORMERS_CACHE: ${TRANSFORMERS_CACHE}
      USE_ONNXRUNTIME_NODE: "0"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - huggingface:${TRANSFORMERS_CACHE}
    depends_on: [db, rabbitmq]
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

volumes:
  pgdata:
  huggingface:
  rabbitmq_data:
