services:
  db:
    image: pgvector/pgvector:pg16
    environment:
      POSTGRES_USER:     postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB:       healthcare
    ports: ["5432:5432"]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db-init:/docker-entrypoint-initdb.d

  app:
    build: .
    ports:
      - "3000:3000"
    develop:
      watch:
        - action: sync
          path: ./src
          target: /src
        - action: rebuild
          path: package.json
    env_file: .env
    environment:
      USE_ONNXRUNTIME_NODE: "0"
    dns:
      - 8.8.8.8
      - 8.8.4.4
    volumes:
      - huggingface:${TRANSFORMERS_CACHE}
    depends_on: [db, rabbitmq]
    restart: unless-stopped

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file: .env
    # Using .env file for RabbitMQ configuration
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq/data

volumes:
  pgdata:
  huggingface:
  rabbitmq_data:
